/**
 * TP1 - IFT585
 * @authors The Team : Benjamin Boudreau (08 318 402), Jean-François Ste-Marie, Jules Deliste, Nicolas Guimier
 */
package ca.usherbrooke.theteam.ift585.tp1.ui;

import ca.usherbrooke.theteam.ift585.tp1.Console;
import ca.usherbrooke.theteam.ift585.tp1.enums.CommunicationProtocol;
import ca.usherbrooke.theteam.ift585.tp1.enums.ValidationAlgorithm;
import ca.usherbrooke.theteam.ift585.tp1.simulation.Simulation;
import ca.usherbrooke.theteam.ift585.tp1.factory.impl.SimulationImpl;
import java.awt.BorderLayout;
import java.awt.Dimension;
import org.apache.log4j.Logger;

/**
 *
 * @author Jules
 */
public class MainFrame extends javax.swing.JFrame {

	private static Logger log = Logger.getLogger(MainFrame.class);

	/** Creates new form UI */
	public MainFrame() {
		initComponents();
		jTextFieldGenerator.setEnabled(rdbCRC.isSelected());
		size = getSize();
		consolePanel = new ConsolePanel();
		Console.getInstance().setConsoleFrame(consolePanel);
		consolePanel.setVisible(false);
		add(consolePanel, BorderLayout.EAST);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    grpValidationAlgorithm = new javax.swing.ButtonGroup();
    grpCommunicationProtocol = new javax.swing.ButtonGroup();
    jPanel1 = new javax.swing.JPanel();
    btnExecute = new javax.swing.JButton();
    mainPanel = new javax.swing.JPanel();
    txtTimeout = new javax.swing.JTextField();
    radioButtonsPanel = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    rdbHammingCode = new javax.swing.JRadioButton();
    rdbCRC = new javax.swing.JRadioButton();
    jTextFieldGenerator = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    rdbSelectiveRejection = new javax.swing.JRadioButton();
    rdbGlobalRejection = new javax.swing.JRadioButton();
    jLabel5 = new javax.swing.JLabel();
    txtInputFile2 = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    txtInputFile1 = new javax.swing.JTextField();
    btnExit = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("[IFT585] TP1 - Main Frame");
    setName("mainFrame"); // NOI18N
    setResizable(false);

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configurations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

    btnExecute.setText("Executer");
    btnExecute.setHideActionText(true);
    btnExecute.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnExecuteActionPerformed(evt);
      }
    });

    txtTimeout.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txtTimeout.setText("7");
    txtTimeout.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Algorithme de validation"));
    jPanel2.setToolTipText("Algorithme de validation");

    grpValidationAlgorithm.add(rdbHammingCode);
    rdbHammingCode.setSelected(true);
    rdbHammingCode.setText("Hamming Code");
    rdbHammingCode.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        crcAction(evt);
      }
    });

    grpValidationAlgorithm.add(rdbCRC);
    rdbCRC.setText("CRC");
    rdbCRC.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        crcAction(evt);
      }
    });

    jTextFieldGenerator.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
    jTextFieldGenerator.setText("1010");

    jLabel2.setText("Générateur:");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(rdbHammingCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addComponent(rdbCRC, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jLabel2)
        .addGap(3, 3, 3)
        .addComponent(jTextFieldGenerator, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addComponent(rdbHammingCode)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(rdbCRC)
          .addComponent(jLabel2)
          .addComponent(jTextFieldGenerator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(10, Short.MAX_VALUE))
    );

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Protocole de communication"));

    grpCommunicationProtocol.add(rdbSelectiveRejection);
    rdbSelectiveRejection.setText("Rejet selectif");

    grpCommunicationProtocol.add(rdbGlobalRejection);
    rdbGlobalRejection.setSelected(true);
    rdbGlobalRejection.setText("Rejet global");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(rdbGlobalRejection, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
      .addComponent(rdbSelectiveRejection, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addComponent(rdbGlobalRejection)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(rdbSelectiveRejection)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout radioButtonsPanelLayout = new javax.swing.GroupLayout(radioButtonsPanel);
    radioButtonsPanel.setLayout(radioButtonsPanelLayout);
    radioButtonsPanelLayout.setHorizontalGroup(
      radioButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(radioButtonsPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(48, 48, 48)
        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(25, 25, 25))
    );
    radioButtonsPanelLayout.setVerticalGroup(
      radioButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(radioButtonsPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(radioButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(radioButtonsPanelLayout.createSequentialGroup()
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
          .addGroup(radioButtonsPanelLayout.createSequentialGroup()
            .addComponent(jPanel2, 0, 91, Short.MAX_VALUE)
            .addContainerGap(14, Short.MAX_VALUE))))
    );

    jLabel5.setLabelFor(txtTimeout);
    jLabel5.setText("Delai d'attente :");

    txtInputFile2.setText("trame1.txt");

    jLabel7.setText("sequences");

    jLabel1.setLabelFor(txtInputFile2);
    jLabel1.setText("Fichier d'entree #2 :");

    jLabel8.setLabelFor(txtInputFile1);
    jLabel8.setText("Fichier d'entree #1 :");

    txtInputFile1.setText("trame.txt");

    javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
    mainPanel.setLayout(mainPanelLayout);
    mainPanelLayout.setHorizontalGroup(
      mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(mainPanelLayout.createSequentialGroup()
        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(mainPanelLayout.createSequentialGroup()
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8))
              .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)))
            .addGap(18, 18, 18)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(txtTimeout, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7))
              .addComponent(txtInputFile1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
              .addComponent(txtInputFile2, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)))
          .addGroup(mainPanelLayout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addComponent(jLabel5))
          .addComponent(radioButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    mainPanelLayout.setVerticalGroup(
      mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(mainPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtInputFile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel8))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(txtInputFile2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(txtTimeout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel7))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(radioButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(66, 66, 66))
    );

    btnExit.setText("Quitter");
    btnExit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnExitActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap(429, Short.MAX_VALUE)
        .addComponent(btnExecute)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnExit)
        .addContainerGap())
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnExit)
          .addComponent(btnExecute))
        .addContainerGap())
    );

    getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
			System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

	/**
	 * Handles the execute button click event.
	 */
    private void btnExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecuteActionPerformed
			if (!inExecution) {
				Console console = Console.getInstance();
				console.clear();
				blockForExecution();
				ConfigurationData configurationData = getFormConfigurationData();
				configurationData.validate();
				if (configurationData.isValid()) {
					simulation = new SimulationImpl(configurationData);
				}
			} else {
				simulation.stop();
				unblockAftetExecution();
			}
    }//GEN-LAST:event_btnExecuteActionPerformed

		private void crcAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crcAction
			jTextFieldGenerator.setEnabled(rdbCRC.isSelected());
		}//GEN-LAST:event_crcAction

	/**
	 * Retrieves the form data and create a ConfigurationData object.
	 * @return The built ConfigurationData object.
	 */
	private ConfigurationData getFormConfigurationData() {
		ConfigurationData configurationData = new ConfigurationData(this);

		if (!txtInputFile1.getText().trim().equals("")) {
			configurationData.setInputFile1(txtInputFile1.getText().trim());
		}

		if (!txtInputFile2.getText().trim().equals("")) {
			configurationData.setInputFile2(txtInputFile2.getText().trim());
		}

		if (grpValidationAlgorithm.getSelection() == rdbCRC.getModel()) {
			configurationData.setValidationAlgorithm(ValidationAlgorithm.CRC);
			configurationData.setCRCgenerator(jTextFieldGenerator.getText());
		} else if (grpValidationAlgorithm.getSelection() == rdbHammingCode.getModel()) {
			configurationData.setValidationAlgorithm(ValidationAlgorithm.HammingCode);
		}

		if (grpCommunicationProtocol.getSelection() == rdbGlobalRejection.getModel()) {
			configurationData.setCommunicationProtocol(CommunicationProtocol.GlobalRejection);
		} else if (grpCommunicationProtocol.getSelection() == rdbSelectiveRejection.getModel()) {
			configurationData.setCommunicationProtocol(CommunicationProtocol.SelectiveRejection);
		}

		try {
			configurationData.setTimeout(Integer.parseInt(txtTimeout.getText()));
		} catch (NumberFormatException e) {
			log.error(e.getMessage());
		}

		return configurationData;
	}
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnExecute;
  private javax.swing.JButton btnExit;
  private javax.swing.ButtonGroup grpCommunicationProtocol;
  private javax.swing.ButtonGroup grpValidationAlgorithm;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JTextField jTextFieldGenerator;
  private javax.swing.JPanel mainPanel;
  private javax.swing.JPanel radioButtonsPanel;
  private javax.swing.JRadioButton rdbCRC;
  private javax.swing.JRadioButton rdbGlobalRejection;
  private javax.swing.JRadioButton rdbHammingCode;
  private javax.swing.JRadioButton rdbSelectiveRejection;
  private javax.swing.JTextField txtInputFile1;
  private javax.swing.JTextField txtInputFile2;
  private javax.swing.JTextField txtTimeout;
  // End of variables declaration//GEN-END:variables
	private ConsolePanel consolePanel;
	private boolean inExecution;
	private Dimension size;
	private Simulation simulation;

	public void blockForExecution() {
		inExecution = true;
		consolePanel.setVisible(true);
		pack();
		btnExecute.setText("Arrêter l'exécution");
		btnExecute.repaint();
	}

	public void unblockAftetExecution() {
		inExecution = false;
		setSize(size);
		consolePanel.setVisible(false);
		btnExecute.setText("Executer");
		btnExecute.repaint();
		pack();
	}
}
